version: '3.8'

services:
  db:
    image: postgres
    restart: 'no'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gopostgres
      DATABASE_HOST: localhost
    ports:
      - '5432:5432'
    networks:
      - default

volumes:
  db-data:

networks:
  default:
